
<style>
.antispam {
	display: none;
}
</style>

<h3>Contact Info</h3>
<p>Do NOT contact us for ANY REASON! But if you do, use this form</p>
<form action="/contact" method="post">
    <table>
        <tr>

            <td>Your name:</td>
            <td><input type="text" name="name" /></td>
        </tr>
        <tr>
            <td>Your email:</td>
            <td><input type="text" name="email" /></td>
        </tr>
        <tr class="antispam">
            <td>Leave this empty:</td>
            <td><input type="text" name="url" /></td>
        </tr>

        <tr>
            <td colspan="2">Your Message:<br /> <textarea rows="10" cols="40" name="message"></textarea></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Send" /></td>
        </tr>


    </table>
</form>
