<?php
// module/Album/view/album/album/add.phtml:
$title = 'Enter Your Commission Request';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array(
    'controller' => 'commission',
    'action' => 'add'
)));
$form->prepare();

?>
<?php echo $this->form()->openTag($form); ?>
<table border=1>
    <thead></thead>
    <tbody>
        <tr colpan="3">
            <td><?php echo $this->formHidden($form->get('id')); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->formLabel($form->get('name')); ?></td>
            <td><?php echo $this->formText($form->get('name')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('name')); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->formLabel($form->get('email')); ?></td>
            <td><?php echo $this->formEmail($form->get('email')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('email')); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->formLabel($form->get('species')); ?></td>
            <td><?php echo $this->formText($form->get('species')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('species')); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->formLabel($form->get('suit-type')); ?></td>
            <td><?php echo $this->formRadio($form->get('suit-type')); ?></td>
            <td><?php echo $this->formElementErrors($form->get('suit-type')); ?></td>
        </tr>
        <tr>
            <td><?php echo $this->formLabel($form->get('character-ref')); ?></td>
            <td><?php echo $this->formFile($form->get('character-ref')); ?></td>
            <td>
                <?php echo $this->formElementErrors($form->get('character-ref')); ?>
                <?php echo $this->escapehtml($this->characterRefFile['name']); ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->formLabel($form->get('request')); ?></td>
            <td colspan="2">
                <?php echo $this->formTextArea($form->get('request')); ?>
            </td>
            <td>
                <?php echo $this->formElementErrors($form->get('request')); ?>
            </td>
        </tr>
        <tr>
            <td></td>
            <td><?php echo $this->formSubmit($form->get('submit')); ?></td>
            <td></td>
        </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag(); ?>