<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Commission\Module'                        => __DIR__ . '/Module.php',
    'CommissionTest\Framework\TestCase'        => __DIR__ . '/tests/Commission/Framework/TestCase.php',
    'CommissionTest\SampleTest'                => __DIR__ . '/tests/Commission/SampleTest.php',
);
