<link rel="stylesheet" href="css/app/reset.css">
<link rel="stylesheet" href="css/app/faq.css">
<script src="js/modernizr.js"></script>
<header>
 <h1>Furries Asking Questions</h1>
</header>
<section class="cd-faq">
 <ul class="cd-faq-categories">
  <li><a class="selected" href="#basics">Basics</a></li>
  <li><a href="#delivery">Delivery</a></li>
 </ul>
 <!-- cd-faq-categories -->

 <div class="cd-faq-items">
  <ul id="basics" class="cd-faq-group">
   <li class="cd-faq-title"><h2>Basics</h2></li>
   <li><a class="cd-faq-trigger" href="#0">How do I sign up?</a>
    <div class="cd-faq-content">
     <p>You Don't!</p>
    </div> <!-- cd-faq-content --></li>

   <li><a class="cd-faq-trigger" href="#0">How do I change my password?</a>
    <div class="cd-faq-content">
     <p>There is no password to change!</p>
    </div> <!-- cd-faq-content --></li>
  </ul>
  <!-- cd-faq-group -->




  <ul id="delivery" class="cd-faq-group">
   <li class="cd-faq-title"><h2>Delivery</h2></li>
   <li><a class="cd-faq-trigger" href="#0">What should I do if my order hasn't been delivered yet?</a>
    <div class="cd-faq-content">
     <p>Just wait impatiently like you've been doing.</p>
    </div> <!-- cd-faq-content --></li>

   <li><a class="cd-faq-trigger" href="#0">How can I find your international delivery information?</a>
    <div class="cd-faq-content">
     <p>We do not ship internationally.</p>
    </div> <!-- cd-faq-content --></li>

   <li><a class="cd-faq-trigger" href="#0">Who takes care of shipping?</a>
    <div class="cd-faq-content">
     <p>Presently we have no one on staff for this position.</p>
    </div> <!-- cd-faq-content --></li>

   <li><a class="cd-faq-trigger" href="#0">How do returns or refunds work?</a>
    <div class="cd-faq-content">
     <p>We simply keep all your money.</p>
    </div> <!-- cd-faq-content --></li>

   <li><a class="cd-faq-trigger" href="#0">How does your Next Day Delivery service work?</a>
    <div class="cd-faq-content">
     <p>It doesn't work.</p>
    </div> <!-- cd-faq-content --></li>

   <li><a class="cd-faq-trigger" href="#0">When will my order arrive?</a>
    <div class="cd-faq-content">
     <p>Our best estimate is usually some time between "now" wand "never".</p>
    </div> <!-- cd-faq-content --></li>

   <li><a class="cd-faq-trigger" href="#0">When will my order ship?</a>
    <div class="cd-faq-content">
     <p>As soon as we complete your order.</p>
    </div> <!-- cd-faq-content --></li>
  </ul>
  <!-- cd-faq-group -->
 </div>
 <!-- cd-faq-items -->
 <a href="#0" class="cd-close-panel">Close</a>
</section>
<!-- cd-faq -->
<script src="js/app/faq.js"></script>
<!-- Resource jQuery -->
